### ISSUE TITLE
Add a switch to emit the full command for every cmd described

### ISSUE THREAD

**Issue by hackedhead** [m3brown/plz#20]
`plz {--describe|--desc|-d}`
Describe each cmd in the config by echoing it's command (list) with the name.

**Comment by hackedhead** [comment]
When I return to a proejct after a hiatus, I run `plz` to see the commands that exist, and then frequently have to follow that up with `cat .plz.yaml` to remind myself what each actually does (mostly in cases where I've used poor names).
It'd be nice to be able to perform that check idiomatically from plz itself.

**Comment by m3brown** [comment]
@hackedhead I haven't released this change yet, but I'm curious if my solution works well enough for that you had in mind.

**Comment by hackedhead** [comment]
Yeah, I think that looks entirely suitable. Thanks!
